config/routes.rb
Makely::Application.routes.draw do

  resources :authentications
  resources :seller_authentications
  resources :sellers
  resources :causes
  resources :categories
  resources :images
  resources :line_items
  resources :finalizedorders

  get '/products/all' => 'products#all_products'
  resources :stores do
    resources :products
  end

  resources :customers do
    resources :orders
  end

  root 'products#all_products'

  resource :my_store

get '/products/sellers_index' => 'products#sellers_index'

get '/customers/:customer_id/orders/:id' => 'orders#show'

end

app/controllers/my_stores_controller.rb
class MyStoresController < ApplicationController

	def index
		
	end

	def show
		@store = current_user.store
	end

end

app/views/my_stores/index.html.erb
<h1>Listing stores</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="2">Store Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>

      <tr>
        <td colspan="2"><%= store.store_name %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New store', new_store_path, class: 'btn btn-default' %>

app/views/my_stores/show.html.erb
<div class="form_container">

	<p id="notice"><%= notice %></p>
	<%= render 'sellers/breadcrumbs' %>

	<div class=".col-xs-12 .col-sm-6 .col-md-8">
	  <div class="row">

	  	<h2>Store Name:</h2>
		<h3> <%= @store.store_name %></h3>

		<h2>Store Info:</h2>
		<h3> <%= @store.store_description %></h3>
		<!-- how to pull up cause name? -->
		<%# @store.cause_name %>

		</br></br></br>

		<%= link_to 'Edit', edit_store_path(@store), class: 'btn btn-default' %> 
		<!-- this link redirects to /stores/:store_id/products/new -->
		<%= link_to 'Create a product', new_store_product_path(@store.id), class: 'btn btn-default' %>

		</br></br></br><p>store id:<%= @store.id%></p>
	  </div>
	</div>
</div>



<%# @store.products.each do |x| %>

	<%# x.product_name %>

	<%# end %>


	<%# link_to "my store", my_store_path %>