config/routes.rb
Makely::Application.routes.draw do

  resources :authentications
  resources :seller_authentications
  resources :sellers
  resources :causes
  resources :categories
  resources :images
  resources :line_items
  resources :finalizedorders

  get '/products/all' => 'products#all_products'
  resources :stores do
    resources :products
  end

  resources :customers do
    resources :orders
  end

  root 'products#all_products'

  resource :my_store

get '/products/sellers_index' => 'products#sellers_index'

get '/customers/:customer_id/orders/:id' => 'orders#show'

end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :cause
  has_many :sellers
  has_many :products
  has_many :orders
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	before_action :set_store, only: [:show, :edit, :update, :destroy]

	# GET /stores
    # GET /stores.json
    def index
    	@stores = Store.all
    end

    # GET /stores/1
  	# GET /stores/1.json
  	def show
		# @store = Store.find(params[:id])
	end
	
	# GET /stores/new
	def new
		@store = Store.new
	end

	# GET /stores/1/edit
	def edit
		# @store = Store.find(params[:id])
  	end

  	# POST /stores
  	# POST /stores.json
	def create
		@store = Store.new(store_params)
		
		@store.sellers << current_user
		# current_user.store_id = @store.find(params[:id])
		# .save?

		# if @store.save
		# 	flash[:notice] = "Store created!"
		# 	redirect_to @store
		# end

		respond_to do |format|

	      if @store.save
	        format.html { redirect_to @store, notice: 'Store was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @store }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @store.errors, status: :unprocessable_entity }
	      end
	    end
	  end
		
		
	# PATCH/PUT /stores/1
  	# PATCH/PUT /stores/1.json
	  def update
	    respond_to do |format|
	      if @store.update(store_params)
	        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: 'edit' }
	        format.json { render json: @store.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # DELETE /stores/1
	  # DELETE /stores/1.json
	  def destroy
	    @store.destroy
	    respond_to do |format|
	      format.html { redirect_to stores_url }
	      format.json { head :no_content }
	    end
	  end

private

	def set_store
      @store = Store.find(params[:id])
    end

	def store_params
      	params.require(:store).permit(:store_name, :store_description, :store_image, :cause_id)
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<div class=".col-xs-12 .col-sm-6 .col-md-8">
  <div class="row">
    <div class ="errors">

      <%= form_for @store, html: {role: "form"} do |f| %>
        <% if @store.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@store.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
            <% @store.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

    <div class="actions">

      <div class="form-group">
      <h3>Cause</h3>
      <%=collection_select(:store, :cause_id, Cause.all, :id, :cause_name, prompt: 'Please select a cause') %>
      </div>

      <div class="form-group">
    	<h3><%= f.label :store_name %></h3>
    	<%= f.text_field :store_name, id:"store_name", class: 'form-control' %>
      <%= @store.errors[:store_username].join(", ") %>
      </div>

      <div class="form-group">
    	<h3><%= f.label :store_description %></h3>
    	<%= f.text_area :store_description, rows: 8, id:"store_description", class: 'form-control'  %>
      <%= @store.errors[:store_description].join(", ") %>
      </div>

      <div class="form-group">
    	<h3><%= f.label :store_image %></h3>
    	<%= f.text_field :store_image, id:"store_image", class: 'form-control' %>
      <%= @store.errors[:store_image].join(", ") %>
      </div>

      <div>
    	<%= f.submit :save, class: 'btn btn-default font' %>
      </div>

    </div>
    <% end %>

     </div>
   </div>
</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<div class="cause_container">
  <% @stores.each do |store| %>
      <div class="col-xs-6 col-md-3">
        <button type="button" class="btn btn-default btn-lg btn-block myBtn"><%= link_to store.store_name, store_products_path(store.id), class: "font" %>
        </button>
      </div>
  <% end %>
</div>

app/views/stores/new.html.erb
<div class="form_container">

<%= render 'sellers/breadcrumbs' %>

<h1>Create a New Store!</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

</div>

app/views/stores/show.html.erb
<div class="form_container">

	<p id="notice"><%= notice %></p>
	
	<%= render 'sellers/breadcrumbs' %>

	<div class=".col-xs-12 .col-sm-6 .col-md-8">
	  <div class="row">

		<h1>Welcome <%= @store.store_name %></h1>

		<h2>Store Name:</h2>
		<h3><%= @store.store_name %></h3>

		<h2>Store Info:</h2>
		<h3><%= @store.store_description %></h3>
		<!-- how to pull up cause name? -->
		<%# @store.cause_name %>

		</br></br></br>

		<%= link_to 'Edit', edit_store_path(@store), class: 'btn btn-default' %> |

		<!-- this link redirects to /stores/:store_id/products/new -->
		<%= link_to 'Create a product', new_store_product_path(@store.id), class: 'btn btn-default' %>


		</br></br></br><p>store id:<%= @store.id%></p>
		</div>

		</div>
	</div>