config/routes.rb
Makely::Application.routes.draw do

  resources :authentications
  resources :seller_authentications
  resources :sellers
  resources :causes
  resources :categories
  resources :images
  resources :line_items
  resources :finalizedorders

  get '/products/all' => 'products#all_products'
  resources :stores do
    resources :products
  end

  resources :customers do
    resources :orders
  end

  root 'products#all_products'

  resource :my_store

get '/products/sellers_index' => 'products#sellers_index'

get '/customers/:customer_id/orders/:id' => 'orders#show'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = Category.find(set_category).products
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category]
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<!-- <h1>Listing Categories</h1> -->

<div class="cause_container">
  <% @categories.each do |category| %>
      <div class="col-xs-6 col-md-3">
        <button type="button" class="btn btn-default btn-lg btn-block myBtn"><%= link_to category.category_name, category, class: "font" %>
        </button>
      </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!-- <h1>Categories Show Page</h1> -->

<button type="button" class="btn btn-default btn-lg btn-block myBtn font">
	<%= @category.category_name %>
</button>

<p id="notice"><%= notice %></p>

<%= link_to 'Back', categories_path %>

<div class="cause_container">
	<% @products.each do |p| %>
		<div class= "product_row">
		  <div class="col-xs-6 col-md-3">
		    <div class="product_img">
		    	<div class="border">
				<span class="prod_pic">
			    	<%= link_to(image_tag(p.picture.url(:thumb)), store_product_path(p.store.id, p.id)) %>
			    	</span>
			    	<span class="caption">
						<h4 class="font"><%= p.product_name %></h4></br>
						<p class="font"><%= p.product_description %></p></br>
						<p class="price"><%= number_to_currency(p.product_price) %></p></br>
						<%# link_to "show product", store_product_url(p.store.id, p.id) %>
					</span>
				</div>
			</div>
		  </div>
		</div>
	<% end %>
</div>

<%# link_to 'Edit', edit_category_path(@category) %> |