config/routes.rb
Makely::Application.routes.draw do

  resources :authentications
  resources :seller_authentications
  resources :sellers
  resources :causes
  resources :categories
  resources :images
  resources :line_items
  resources :finalizedorders

  get '/products/all' => 'products#all_products'
  resources :stores do
    resources :products
  end

  resources :customers do
    resources :orders
  end

  root 'products#all_products'

  resource :my_store

get '/products/sellers_index' => 'products#sellers_index'

get '/customers/:customer_id/orders/:id' => 'orders#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :store
  has_many :images

  has_many :line_items

  # before_destroy :ensure_not_referenced_by_any_line_item

  has_attached_file :picture, :styles => { :show => "800x400>", :medium => "300x300>", :thumb => "175x175>", :sm_thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  # :storage => :s3,
  # :s3_credentials => {:bucket => ENV['AWS_BUCKET'],
  #                     :access_key_id     => ENV['AWS_ACCESS_KEY_ID'],
  #                     :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']},
  # :s3_protocol    => "https",
  # :s3_host_name   => "s3-us-west-2.amazonaws.com"


  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end

  end
  

 #  validates :product_name, :product_description, :product_image, presence: true
 #  validates :product_price, numericality: {greater_than_or_equal_to: 0.01}
 #  validates :image_url, allow_blank: true, format: {
 #    with:    %r{\.(gif|jpg|png)\Z}i,
	# message: 'must be a URL for GIF, JPG or PNG image.' }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentOrder
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_action :set_order, only: [:edit, :update, :destroy]
  before_action :set_order, only: [:update]

  # GET /store/:store_id/products
  # GET /store/:store_id/products.json
  def index
    # store = Store.find(params[:store_id])
    # @products = store.products
    
    @store = Store.find(params[:store_id])
    @products = @store.products
  end

  def all_products
    @products = Product.all.order(:category_id)
  end

  # GET /store/:store_id/products/1
  # GET /store/:store_id/products/1.json
  def show
    # @image = @product.images.find(product)
   
  end

  # GET /store/:store_id/products/new
  def new
    store = Store.find(params[:store_id])
    @product = store.products.build
  end

  # GET /store/:store_id/products/1/edit
  def edit
  end

  def sellers_index
    # @sellers = Seller.all
    # @store = Store.find(params[:store_id])
    # @store = current_user.store_id
    @store = current_user.store
    @products = @store.products
    # @product = @store.products.find(params[:id])
  end 

  # POST /store/:store_id/products
  # POST /store/:store_id/products.json
  def create
    # logger.info params[:images][:direct_upload_url]
    store = Store.find(params[:store_id])
    @product = store.products.create(product_params)
    @product.picture = params[:product][:picture] 
    # @image = @product.images.create!(image_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to([@product.store, @product], notice: 'Product was successfully created.') }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store/:store_id/products/1
  # PATCH/PUT /store/:store_id/products/1.json
  def update
    # store = Store.find(params[:store_id])
    # @product = store.products.create(product_params)
    # @image = @product.images.create!(image_params)
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to([@product.store, @product], notice: 'Product was successfully updated.') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store/:store_id/products/1
  # DELETE /store/:store_id/products/1.json
  def destroy
    # @store = Store.find(params[:store_id])
    # @store.products.find(params[:id]).destroy
    @product.destroy
    respond_to do |format|
      # format.html { redirect_to store_products_url }
      format.html { redirect_to products_sellers_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      #1st you retrieve the store 
      @store = Store.find(params[:store_id])
      #2nd you retrieve the product.  
      @product = @store.products.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      # params[:product]
      params.require(:product).permit(:product_name, :product_description, :product_price, :picture, :store_id, :category_id)
    end

    # def image_params
    #     params.require(:image).permit(:direct_upload_url)
    # end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class=".col-xs-12 .col-sm-6 .col-md-8">
  <div class="row">
    <div class ="errors">

    <%= form_for [@product.store, @product], html: {role: "form"} do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <div class="actions">

      <div class="form-group">
      <h3>Category</h3>
      <%=collection_select(:product, :category_id, Category.all, :id, :category_name, prompt: 'Please select a category') %>
      </div>   



          <div class="form-group">
          <h3><%= f.label :product_name %></h3>
          <%= f.text_area :product_name, rows: 2,id:"product_name", class: 'form-control' %>
          <%= @product.errors[:product_name].join(", ") %>
          </div>


          <div class="form-group">
          <h3><%= f.label :product_description %></h3>
          <%= f.text_area :product_description, rows: 8, id:"product_description", class: 'form-control' %>
          <%= @product.errors[:product_description].join(", ") %>
          </div>


          <div class="form-group">
          <h3><%= f.label :product_price %></h3>
          <%= f.text_area :product_price, rows: 2, id:"product_price", class: 'form-control' %>
          <%= @product.errors[:product_price].join(", ") %>
          </div>

          <div class="form-group">
          <h3><%= f.label :product_picture %></h3>
          <!-- this one works -->
          <%= f.file_field :picture %></br>
          <%# f.file_field :image %>
          <%# f.text_field :product_image, id:"product_image", class: 'form-control' %>
          <%= @product.errors[:product_image].join(", ") %>
          </div>

    
            <div>
            <%= f.submit :save, class: 'btn btn-default font' %>
            </div>

    </div>
    <% end %>


    


    </div>
  </div>
</div>

app/views/products/_products_index.html.erb
<h1>Listing products</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="2">Product Name</th>
      <th>Product Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>

      <tr>
        <td colspan="2"><%= product.product_name %></td>
        <td><%= product.product_description %></td>
        <td><%= button_to 'Add to Cart', line_items_path(product_id: product) %></td>
        <td><%= link_to 'Show', [product.store, product] %></td>
        <td><%= link_to 'Edit', edit_store_product_path(product.store, product) %></td>
        <td><%= link_to 'Destroy', [product.store, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_store_product_path, class: 'btn btn-default' %>

app/views/products/_store_products_page.html.erb
<!-- <h1>Stores Show Page</h1> -->

<button type="button" class="btn btn-default btn-lg btn-block myBtn font">
	<%= @store.store_name %>
</button>

<p id="notice"><%= notice %></p>


<%= link_to 'Back', stores_path %>

<div class="cause_container">
	<% @products.each do |p| %>
		<div class= "product_row">
		  <div class="col-xs-6 col-md-3">
		    <div class="product_img">
		    	<div class="border">
		    	<span class="prod_pic">
			    	<%= link_to(image_tag(p.picture.url(:thumb)), store_product_path(p.store.id, p.id)) %>
			    	</span>
			    	<span class="caption">
						<h4 class="font"><%= p.product_name %></h4></br>
						<p class="font"><%= p.product_description %></p></br>
						<p class="price"><%= number_to_currency(p.product_price) %></p></br>
						<%# link_to "show product", store_product_url(p.store.id, p.id) %>
					</span> %>
				</div>
			</div>
		  </div>
		</div>
	<% end %>
</div>

<%# link_to 'Edit', edit_category_path(@category) %> |

app/views/products/all_products.html.erb
<!-- <h1>All Products Show Page</h1> -->

<p id="notice"><%= notice %></p>

<%# link_to 'Back', causes_path %>

<div id="cause_container">
	<% @products.each do |p| %>
		<div class= "product_row">
		  <div class="col-xs-6 col-md-3">
		    <div class="product_img">
		    	<div class="border">
			    	<span class="prod_pic">
			    	<%= link_to(image_tag(p.picture.url(:thumb)), store_product_path(p.store.id, p.id)) %>
			    	</span>
			    	<span class="caption">
						<h4 class="font"><%= p.product_name %></h4></br>
						<p class="font"><%= p.product_description %></p></br>
						<p class="price"><%= number_to_currency(p.product_price) %></p></br>
						<%# link_to "show product", store_product_url(p.store.id, p.id) %>
					</span>
				 </div>
			</div>
		  </div>
		</div>
	<% end %>
</div>
</div>

<script>
var initTopPosition= $('#myElementToStick').offset().top;
$(window).scroll(function(){
    if($(window).scrollTop() > initTopPosition - 60)
        $('#myElementToStick').css({'position':'fixed','top':'60px', 'width':'110%'});
    else
        $('#myElementToStick').css({'position':'absolute','top':initTopPosition+'px'});
});

</script>

app/views/products/create.js.erb
<% if @image.persisted? %>
  $('#upload_<%=params[:unique_id]%>').hide();
<% else %>
  $('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped').addClass('progress-danger');
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<% if @seller %>
<%= render 'products_index' %>
<% else %>
<%= render 'store_products_page' %>
<% end %> 



<!-- <h1>Listing products</h1> -->

<!-- <table class="table table-hover">
  <thead>
    <tr>
      <th colspan="2">Product Name</th>
      <th>Product Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>

  <%# cache ['store', Product.latest] do %>
    <%#@products.each do |product| %>

      <tr>
        <td colspan="2"><%# product.product_name %></td>
        <td><%# product.product_description %></td>
        <td><%# button_to 'Add to Cart', line_items_path(product_id: product) %></td>
        <td><%# link_to 'Show', [product.store, product] %></td>
        <td><%# link_to 'Edit', edit_store_product_path(product.store, product) %></td>
        <td><%# link_to 'Delete', [product.store, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <%#end %>

  </tbody>
</table>

<br> -->

<%# link_to 'New Product', new_store_product_path, class: 'btn btn-default' %>

app/views/products/new.html.erb
<div class="form_container">

<%= render 'sellers/breadcrumbs' %>

<h1>New Product</h1>

<%= render 'form' %>


<!-- <h3 id="drag-here">Drag all photos here</h3> -->
<%# s3_uploader_form callback_url: images_url, id: "s3-uploader", callback_param: "image[direct_upload_url]", expiration: 24.hours.from_now.utc.iso8601, max_file_size: 5.megabytes do %>
<%# hidden_field_tag  "Content-type", "" %>
<%# file_field_tag :file, multiple: true %>

<%# end %>  <!-- was this a problem? -->

<!-- <div id="uploads_container"></div> -->

<%= link_to 'Back', store_products_path %>

</div>

app/views/products/sellers_index.html.erb
<div class = "shopping_container">
  <h1>Listing Products</h1>
  <div class="checkout_form">

  <table class="table table-hover">
    <thead>
      <tr>
        <th colspan="2">Product Name</th>
        <th>Product Description</th>
        <th></th>
      </tr>
    </thead>

    <tbody>

    <%# cache ['store', Product.latest] do %>
      <% @products.each do |product| %>

        <tr>
          <td colspan="2"><%= product.product_name %></td>
          <td><%= product.product_description %></td>
          <td><%# button_to 'Add to Cart', [product.store, product] %></td>
          <!-- <td><%# button_to 'Add to Cart', line_items_path(product_id: product) %></td> -->
          <!-- <td><%# button_to 'Add to Cart', line_items_path(product.store, product_id) %></td> -->

          <td><%= link_to 'Show', [product.store, product] %></td>
          <td><%= link_to 'Edit', edit_store_product_path(product.store, product) %></td>
          <td><%= link_to 'Delete', [product.store, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
    </br>
    <%= link_to 'Create a product', new_store_product_path(@store.id), class: 'btn btn-default' %>
    <%# end %>
  </tbody>
</table>


  </div>
</div>

app/views/products/show.html.erb
<!-- <h1>Product Show Page</h1> -->

<p id="notice"><%= notice %></p>

<div class="product_container">
	<!-- LEFT COLUMN -->
	<div class="col-xs-12 col-md-8">
		<!-- PRODUCT IMAGE -->
	    <div class="product_show_img">
	    	<div class="prod_show_border">
		    	<%= image_tag @product.picture.url(:show) %>
		    </div>
		</div>

		<!-- PRODUCT THUMBNAILS
		<div class="product_thumbnails">
				<div class="prod_thumb">
		    		<div class="prod_border">
		    			<p class="font">product image</p>
		    		</div>
		    	</div>
		    	<div class="prod_thumb">
		    		<div class="prod_border">
		    			<p class="font">product image</p>
		    		</div>
		    	</div>
		    	<div class="prod_thumb">
		    		<div class="prod_border">
		    			<p class="font">product image</p>
		    		</div>
		    	</div>
		    	<div class="prod_thumb">
		    		<div class="prod_border">
		    			<p class="font">product image</p>
		    		</div>
		    	</div>
		</div> -->

		<!-- PRODUCT INFO -->
		<div class="product_info">
			<!-- Nav tabs -->
			<ul class="nav nav-tabs font">
			  <li><a href="#home" data-toggle="tab">Product Info</a></li>
			  <li><a href="#profile" data-toggle="tab">Shipping Info</a></li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content font">
			  <div class="tab-pane active" id="home">
				  	<h2 class="font"><%= @product.product_name %></h2></br>
					<h3 class="font"><%= @product.product_description %></h3></br>
					<h3 class="price font"><%= number_to_currency(@product.product_price) %></h3></br>
	 		  </div>
			  
			  <div class="tab-pane" id="profile">
			  		<h2 class="font">This is where shipping info goes</h2>
			  </div>
			</div>
		</div>
	</div>

	<!-- RIGHT COLUMN -->
	<div class="col-xs-6 col-md-4">
		<!-- SHOPPING CART -->
		<div class="cart">
			<h2 class="font">Shopping Cart</h2>
				<div class="cart_border">
				<!-- <button type="button" class="btn btn-default btn-lg btn-block myBtn"> -->
				
				<%= button_to 'Add to Cart', line_items_path(product_id: @product), id: "cart_btn", class: "btn btn-default myBtn font" %>

				<%# if current_customer_user %>
				<%# button_to 'Add to Cart', line_items_path(product_id: @product), id: "cart_btn", class: "btn btn-default myBtn font" %>
				<%# else %>
				<%# button_to 'Login to Add to Cart', new_authentication_path(@authentications), id: "cart_btn", class: "btn btn-default myBtn font" %>
				<%# end %>
				<!-- authentications/customer_login -->
				<!-- </button> -->
				</div>
		</div>

		<!-- CATEGORY/CAUSE BUTTON -->
		<div class="category_info">
			<h4 class="font">Cause</h4>
			<button type="button" class="btn btn-default myBtn_sm"><%= link_to @store.cause.cause_name, @store.cause, class: "font" %>
			</button>

			<h4 class="font">Category</h4>
			<button type="button" class="btn btn-default myBtn_sm"><%= link_to @product.category.category_name, @product.category, class: "font" %>
			</button>
		</div>

		<!-- STORE INFO -->
		<div class="store_info">
			<h1 class="font"><%= @store.store_name %></h1>
				<div class="store_border">
					<h2 class="font">Store Info</h2>
					<h3 class="font"><%= @store.store_description %></h3>
				</div>
		</div>

		<!-- ADDITIONAL STORE PRODUCTS -->
		<div class="store_prods">
			<h2 class="font">More Store Products</h2>
				<% @store.products.each do |p| %>
				<div class="store_prod_border">
					<div class="prod_thumb r">
			    		<div class="prod_border">	
			    			<span class="sm_prod_pic">
					    	<%= link_to(image_tag(p.picture.url(:sm_thumb)), store_product_path(p.store.id, p.id)) %>
					    	</span>
					    	<span class="caption">
			    			<p class="font"><%= p.product_name %></p></br>
			    			</span>
			    		</div>
		    		</div>
		    	 <% end %>
	    		</div>
		</div>
	</div>
</div>
</div>
</div>


<%# link_to 'Edit', edit_store_product_path %> 
<%# link_to 'Back', store_products_path %>